// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package example

import (
	"os"
)

// Injectors from wire.go:

func GetPostService() (*PostService, func(), error) {
	iPostRepo, cleanup, err := NewPostRepo()
	if err != nil {
		return nil, nil, err
	}
	postUsecase, cleanup2, err := NewPostUsecase(iPostRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	int2 := _wireIntValue
	reader := _wireFileValue
	postService := &PostService{
		usecase: postUsecase,
		a:       int2,
		r:       reader,
	}
	return postService, func() {
		cleanup2()
		cleanup()
	}, nil
}

var (
	_wireIntValue  = 10
	_wireFileValue = os.Stdin
)
