version: '3.5'
# 网络配置
networks:
  backend:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_USER=admin                  # 设置 Mysql 用户名称
      - MYSQL_PASSWORD=123456              # 设置 Mysql 用户密码
      - MYSQL_ROOT_PASSWORD=123456    # 设置 Mysql root 用户密码
    privileged: true
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"                          # 设置容器3306端口映射指定宿主机端口
    networks:
      - backend
    restart: always
